const RIDE_STATUS = {
  SEARCHING_DRIVER: "SEARCHING_DRIVER",
  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",
  DRIVER_ARRIVING: "DRIVER_ARRIVING",
  VERIFY_CODE: "VERIFY_CODE",
  ON_TRIP: "ON_TRIP",
  COMPLETED: "COMPLETED",
  CANCELLED_BY_CUSTOMER: "CANCELLED_BY_CUSTOMER",
  CANCELLED_BY_DRIVER: "CANCELLED_BY_DRIVER",
  EXPIRED: "EXPIRED",
  NO_DRIVER_AVAILABLE: "NO_DRIVER_AVAILABLE",
};

const CUSTOMER_STATUS = {
  ACTIVE: "ACTIVE",
  BLOCKED: "BLOCKED",
};

const DRIVER_STATUS = {
  OFFLINE: "OFFLINE",
  ONLINE: "ONLINE",
  BUSY: "BUSY",
};

const PAYMENT_METHOD = {
  UPI: "UPI",
  CASH: "CASH",
};

const RIDE_TYPE = {
  SHARED: "shared",
  PERSONAL: "personal",
};

const TRIP_EVENT = {
  CREATED: "CREATED",
  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",
  DRIVER_ARRIVING: "DRIVER_ARRIVING",
  OTP_READY: "OTP_READY",
  STARTED: "STARTED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

const SOCKET_EVENT = {
  RIDE_SEARCHING: "ride:searching",
  DRIVER_ASSIGNED: "ride:driver_assigned",
  DRIVER_LOCATION: "ride:driver_location",
  DRIVER_ARRIVING: "ride:driver_arriving",
  OTP_READY: "ride:otp_ready",
  STARTED: "ride:started",
  COMPLETED: "ride:completed",
  CANCELLED: "ride:cancelled",
  WALLET_UPDATED: "wallet:updated",
};

const ACTIVE_RIDE_STATUSES = [
  RIDE_STATUS.SEARCHING_DRIVER,
  RIDE_STATUS.DRIVER_ASSIGNED,
  RIDE_STATUS.DRIVER_ARRIVING,
  RIDE_STATUS.VERIFY_CODE,
  RIDE_STATUS.ON_TRIP,
];

const TERMINAL_RIDE_STATUSES = [
  RIDE_STATUS.COMPLETED,
  RIDE_STATUS.CANCELLED_BY_CUSTOMER,
  RIDE_STATUS.CANCELLED_BY_DRIVER,
  RIDE_STATUS.EXPIRED,
  RIDE_STATUS.NO_DRIVER_AVAILABLE,
];

const POPULAR_LOCATIONS = {
  Jammu: [
    "Railway Station", "Bus Stand", "Airport", "Raghunath Market",
    "Gandhi Nagar", "Bakshi Nagar", "Trikuta Nagar", "GMC Hospital",
    "Canal Road", "Parade Ground", "Residency Road", "Talab Tillo",
    "Nagrota", "Kunjwani", "Janipur",
  ],
  Delhi: ["Connaught Place", "Dwarka", "Rohini", "Karol Bagh", "Saket", "IGI Airport"],
};

module.exports = {
  ACTIVE_RIDE_STATUSES,
  CUSTOMER_STATUS,
  DRIVER_STATUS,
  PAYMENT_METHOD,
  POPULAR_LOCATIONS,
  RIDE_STATUS,
  RIDE_TYPE,
  SOCKET_EVENT,
  TERMINAL_RIDE_STATUSES,
  TRIP_EVENT,
};
